from typing import Any, Dict, List, Optional, Union
from enum import Enum
from pydantic import BaseModel, Field
from .holdings_override import HoldingsOverride
from .income_override import IncomeOverride
from .inflow_model import InflowModel
from .investments_transactions_override import InvestmentsTransactionsOverride
from .liability_override import LiabilityOverride
from .meta import Meta
from .numbers import Numbers
from .owner_override import OwnerOverride
from .transaction_override import TransactionOverride


class OverrideAccounts(BaseModel):
    """If provided, the account will start with this amount as the current balance."""

    starting_balance: float
    """The `inflow_model` allows you to model a test account that receives regular income or make regular payments on a loan. Any transactions generated by the `inflow_model` will appear in addition to randomly generated test data or transactions specified by `override_accounts`."""
    inflow_model: InflowModel
    """Specify payroll data on the account."""
    income: Optional[IncomeOverride] = None
    """Specify the list of transactions on the account."""
    transactions: List[TransactionOverride]
    """Allows specifying the metadata of the test account"""
    meta: Meta
    """`investment:` Investment account.
    
    `credit:` Credit card
    
    `depository:` Depository account
    
    `loan:` Loan account
    
    `payroll:` Payroll account
    
    `other:` Non-specified account type
    
    See the [Account type schema](https://plaid.com/docs/api/accounts#account-type-schema) for a full listing of account types and corresponding subtypes."""
    type: str
    """If provided, the account will always have this amount as its  available balance, regardless of current balance or changes in transactions over time."""
    force_available_balance: float
    """ISO-4217 currency code. If provided, the account will be denominated in the given currency. Transactions will also be in this currency by default."""
    currency: str
    """Account and bank identifier number data used to configure the test account. All values are optional."""
    numbers: Numbers
    """Specify the holdings on the account."""
    holdings: Optional[HoldingsOverride] = None
    """See the [Account type schema](https://plaid.com/docs/api/accounts/#account-type-schema) for a full listing of account types and corresponding subtypes."""
    subtype: Optional[str] = None
    """Specify the list of investments transactions on the account."""
    investment_transactions: Optional[InvestmentsTransactionsOverride] = None
    """Used to configure Sandbox test data for the Liabilities product"""
    liability: LiabilityOverride
    """Data about the owner or owners of an account. Any fields not specified will be filled in with default Sandbox information."""
    identity: OwnerOverride

    def json(self, **kwargs: Any) -> str:
        """Return a json string representation of the object. Takes same keyword arguments as pydantic.BaseModel.json"""
        kwargs.setdefault("by_alias", True)
        return super().json(**kwargs)

    def dict(self, **kwargs: Any) -> Dict[str, Any]:
        """Return a dict representation of the object. Takes same keyword arguments as pydantic.BaseModel.dict"""
        kwargs.setdefault("by_alias", True)
        return super().dict(**kwargs)

    @classmethod
    def parse_obj(cls, data: Any) -> "OverrideAccounts":
        """Parse a dict into the object. Takes same keyword arguments as pydantic.BaseModel.parse_obj"""
        return super().parse_obj(data)

    @classmethod
    def parse_raw(cls, b: Union[bytes, str], **kwargs: Any) -> "OverrideAccounts":
        """Parse a json string into the object. Takes same keyword arguments as pydantic.BaseModel.parse_raw"""
        return super().parse_raw(b, **kwargs)
